source 'https://rubygems.org'

gem 'rails', '~> 4.0'

# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.3.0'

# Use Puma as the app server
gem 'puma', '~> 3.0'

# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'

# OmniAuth strategy for authenticating with Auth0
gem 'omniauth-auth0', git: 'https://github.com/mlsquires/omniauth-auth0.git', branch: 'skip_info'
# gem 'omniauth-rails_csrf_protection', '~> 0.1'
gem 'oauth2', git: 'https://github.com/mlsquires/oauth2.git', branch: '1-4-logging'
gem 'omniauth', '= 1.4.2'
gem 'omniauth-oauth2', '= 1.5.0'

# gem 'lograge'
gem 'awesome_print'

# group :development, :test do
#   # Call 'byebug' anywhere in the code to stop execution and get a debugger console
#   gem 'byebug', platform: :mri
# end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
#   gem 'web-console'
#  gem 'listen', '~> 3.0.5'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'pry'
  gem 'dotenv', '~> 0.11.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
# gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
